### ISSUE TITLE
Enabling connection encryption by default on PyExasol

### ISSUE THREAD

**Issue by exa-mohamedi** [exasol/pyexasol#84]
From Exasol DB 8.0 and SaaS onwards, the DB will be configured to accept only encrypted connections by default which will cause the unencrypted connections to be denied.

By default, the pyexasol establish an unencrypted connection ([PyExasol Doc](https://github.com/exasol/pyexasol/blob/master/docs/REFERENCE.md#:~:text=use%20ssl%20encryption%20for%20websocket%20communication%20and%20http%20transport%20(default%3A%20false))) to DB which will cause the connection to fail on DB 8.0 onwards.

It would be better to update the PyExasol to establish an encrypted connection to DB as an default connection.

**Comment by littleK0i** [comment]
It's a very good question.

I suspect, at this moment we have far more users on older Exasol versions, and this change might break the existing scripts for them. Also, most users with "on-premise" Exasol installations do not really need this extra SSL security layer, since they already use VPN, encrypted tunnels, etc.

It will just waste CPU cycles with very little extra security. The last time we tested performance difference (a few years ago) it was about ~10-20%. I think it got cheaper since then, but it's not free, especially for large volumes of data.

---

On the other hand, if you know that most customers accepted this overhead, and if you agree that Exasol performance will look worse during POCs, I'll change this default.

Thank you.

**Comment by littleK0i** [comment]
(Waiting for Exasol R&D team to finish tests and come back with final conclusion on this issue)

**Comment by ThomasBestfleisch** [comment]
@littleK0i  As discussed let's go ahead and set encrpytion as default.

**Comment by exa-mohamedi** [comment]
@littleK0i, Thanks
